// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/proto/gpu/gpu.proto

package gpu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamRequest is sent by the server to initiate the metric stream.
type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How often the agent should collect and send metrics, in milliseconds.
	IntervalMs    int64 `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_internal_proto_gpu_gpu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gpu_gpu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gpu_gpu_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

// MetricSnapshot is a point-in-time snapshot of all GPUs on a node.
type MetricSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // Unix epoch milliseconds
	Gpus          []*GPUMetric           `protobuf:"bytes,3,rep,name=gpus,proto3" json:"gpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSnapshot) Reset() {
	*x = MetricSnapshot{}
	mi := &file_internal_proto_gpu_gpu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSnapshot) ProtoMessage() {}

func (x *MetricSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gpu_gpu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSnapshot.ProtoReflect.Descriptor instead.
func (*MetricSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_proto_gpu_gpu_proto_rawDescGZIP(), []int{1}
}

func (x *MetricSnapshot) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *MetricSnapshot) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MetricSnapshot) GetGpus() []*GPUMetric {
	if x != nil {
		return x.Gpus
	}
	return nil
}

// GPUMetric holds metrics for a single GPU device.
type GPUMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Vendor        string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"` // "nvidia" | "amd" | "intel"
	UtilPercent   float64                `protobuf:"fixed64,5,opt,name=util_percent,json=utilPercent,proto3" json:"util_percent,omitempty"`
	VramUsedMb    uint64                 `protobuf:"varint,6,opt,name=vram_used_mb,json=vramUsedMb,proto3" json:"vram_used_mb,omitempty"`
	VramTotalMb   uint64                 `protobuf:"varint,7,opt,name=vram_total_mb,json=vramTotalMb,proto3" json:"vram_total_mb,omitempty"`
	TempCelsius   float64                `protobuf:"fixed64,8,opt,name=temp_celsius,json=tempCelsius,proto3" json:"temp_celsius,omitempty"`
	PowerWatts    float64                `protobuf:"fixed64,9,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUMetric) Reset() {
	*x = GPUMetric{}
	mi := &file_internal_proto_gpu_gpu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetric) ProtoMessage() {}

func (x *GPUMetric) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gpu_gpu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetric.ProtoReflect.Descriptor instead.
func (*GPUMetric) Descriptor() ([]byte, []int) {
	return file_internal_proto_gpu_gpu_proto_rawDescGZIP(), []int{2}
}

func (x *GPUMetric) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUMetric) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GPUMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUMetric) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPUMetric) GetUtilPercent() float64 {
	if x != nil {
		return x.UtilPercent
	}
	return 0
}

func (x *GPUMetric) GetVramUsedMb() uint64 {
	if x != nil {
		return x.VramUsedMb
	}
	return 0
}

func (x *GPUMetric) GetVramTotalMb() uint64 {
	if x != nil {
		return x.VramTotalMb
	}
	return 0
}

func (x *GPUMetric) GetTempCelsius() float64 {
	if x != nil {
		return x.TempCelsius
	}
	return 0
}

func (x *GPUMetric) GetPowerWatts() float64 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

var File_internal_proto_gpu_gpu_proto protoreflect.FileDescriptor

const file_internal_proto_gpu_gpu_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/gpu/gpu.proto\x12\x03gpu\"0\n" +
	"\rStreamRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x03R\n" +
	"intervalMs\"t\n" +
	"\x0eMetricSnapshot\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\"\n" +
	"\x04gpus\x18\x03 \x03(\v2\x0e.gpu.GPUMetricR\x04gpus\"\x8e\x02\n" +
	"\tGPUMetric\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12!\n" +
	"\futil_percent\x18\x05 \x01(\x01R\vutilPercent\x12 \n" +
	"\fvram_used_mb\x18\x06 \x01(\x04R\n" +
	"vramUsedMb\x12\"\n" +
	"\rvram_total_mb\x18\a \x01(\x04R\vvramTotalMb\x12!\n" +
	"\ftemp_celsius\x18\b \x01(\x01R\vtempCelsius\x12\x1f\n" +
	"\vpower_watts\x18\t \x01(\x01R\n" +
	"powerWatts2J\n" +
	"\fAgentService\x12:\n" +
	"\rStreamMetrics\x12\x12.gpu.StreamRequest\x1a\x13.gpu.MetricSnapshot0\x01B0Z.github.com/yourorg/kgpudash/internal/proto/gpub\x06proto3"

var (
	file_internal_proto_gpu_gpu_proto_rawDescOnce sync.Once
	file_internal_proto_gpu_gpu_proto_rawDescData []byte
)

func file_internal_proto_gpu_gpu_proto_rawDescGZIP() []byte {
	file_internal_proto_gpu_gpu_proto_rawDescOnce.Do(func() {
		file_internal_proto_gpu_gpu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_gpu_gpu_proto_rawDesc), len(file_internal_proto_gpu_gpu_proto_rawDesc)))
	})
	return file_internal_proto_gpu_gpu_proto_rawDescData
}

var file_internal_proto_gpu_gpu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_gpu_gpu_proto_goTypes = []any{
	(*StreamRequest)(nil),  // 0: gpu.StreamRequest
	(*MetricSnapshot)(nil), // 1: gpu.MetricSnapshot
	(*GPUMetric)(nil),      // 2: gpu.GPUMetric
}
var file_internal_proto_gpu_gpu_proto_depIdxs = []int32{
	2, // 0: gpu.MetricSnapshot.gpus:type_name -> gpu.GPUMetric
	0, // 1: gpu.AgentService.StreamMetrics:input_type -> gpu.StreamRequest
	1, // 2: gpu.AgentService.StreamMetrics:output_type -> gpu.MetricSnapshot
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_gpu_gpu_proto_init() }
func file_internal_proto_gpu_gpu_proto_init() {
	if File_internal_proto_gpu_gpu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gpu_gpu_proto_rawDesc), len(file_internal_proto_gpu_gpu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gpu_gpu_proto_goTypes,
		DependencyIndexes: file_internal_proto_gpu_gpu_proto_depIdxs,
		MessageInfos:      file_internal_proto_gpu_gpu_proto_msgTypes,
	}.Build()
	File_internal_proto_gpu_gpu_proto = out.File
	file_internal_proto_gpu_gpu_proto_goTypes = nil
	file_internal_proto_gpu_gpu_proto_depIdxs = nil
}
