---
apiVersion: v1
kind: Namespace
metadata:
  name: kgpudash

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kgpudash-server
  namespace: kgpudash

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kgpudash-server
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kgpudash-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kgpudash-server
subjects:
  - kind: ServiceAccount
    name: kgpudash-server
    namespace: kgpudash
